"""empty message

Revision ID: 618d53a7f543
Revises: 9efca38a9b66
Create Date: 2020-03-10 11:43:22.061818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618d53a7f543'
down_revision = '9efca38a9b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('create_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'create_date')
    # ### end Alembic commands ###
