"""empty message

Revision ID: 92f48d874fa9
Revises: 618d53a7f543
Create Date: 2020-03-10 12:05:09.425804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f48d874fa9'
down_revision = '618d53a7f543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('created_date', sa.String(length=80), nullable=True))
    op.drop_column('user_profiles', 'create_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('create_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'created_date')
    # ### end Alembic commands ###
